quranNumToSurah = {
	1:	"Al-Fatihah",
	2:	"Al-Baqarah",
	3:	"Al-Imran",
	4:	"An-Nisa'",
	5:	"Al-Ma'idah",
	6:	"Al-An'am",
	7:	"Al-A'raf",
	8:	"Al-Anfal",
	9:	"At-Taubah",
	10:	"Yunus",
	11:	"Hud",
	12:	"Yusuf",
	13:	"Ar-Ra'd",
	14:	"Ibrahim",
	15:	"Al-Hijr",
	16:	"An-Nahl",
	17:	"Al-Isra",
	18:	"Al-Kahf",
	19:	"Maryam",
	20:	"Ta Ha",
	21:	"Al-Anbiya'",
	22:	"Al-Hajj",
	23:	"Al-Mu'minun",
	24:	"An-Nur",
	25:	"Al-Furqan",
	26:	"Ash-Shu'ara",
	27:	"An-Naml",
	28:	"Al-Qasas",
	29:	"Al-'Ankabut",
	30:	"Ar-Rum",
	31:	"Luqman",
	32:	"As-Sajdah",
	33:	"Al-Ahzab",
	34:	"Saba'",
	35:	"Fatir",
	36:	"Ya Sin",
	37:	"As-Saffat",
	38:	"Sad",
	39:	"Az-Zumar",
	40:	"Ghafir",
	41:	"Fussilat",
	42:	"Ash-Shura",
	43:	"Az-Zukhruf",
	44:	"Ad-Dukhan",
	45:	"Al-Jathiyah",
	46:	"Al-Ahqaf",
	47:	"Muhammad",
	48:	"Al-Fath",
	49:	"Al-Hujurat",
	50:	"Qaf",
	51:	"Ad-Dhariyat",
	52:	"At-Tur",
	53:	"An-Najm",
	54:	"Al-Qamar",
	55:	"Ar-Rahman",
	56:	"Al-Waqi'ah",
	57:	"Al-Hadid",
	58:	"Al-Mujadilah",
	59:	"Al-Hashr",
	60:	"Al-Mumtahanah",
	61:	"As-Saff",
	62:	"Al-Jumu'ah",
	63:	"Al-Munafiqun",
	64:	"At-Taghabun",
	65:	"At-Talaq",
	66:	"At-Tahrim",
	67:	"Al-Mulk",
	68:	"Al-Qalam",
	69:	"Al-Haqqah",
	70:	"Al-Ma'arij",
	71:	"Nuh",
	72:	"Al-Jinn",
	73:	"Al-Muzammil",
	74:	"Al-Mudathir",
	75:	"Al-Qiyamah",
	76:	"Al-Insane",
	77:	"Al-Mursalat",
	78:	"An-Naba'",
	79:	"An-Nazi'at",
	80:	"'Abasa",
	81:	"At-Takwir",
	82:	"Al-Infitar",
	83:	"Al-Mutaffifeen",
	84:	"Al-Inshiqaq",
	85:	"Al-Buruj",
	86:	"At-Tariq",
	87:	"Al-A`la",
	88:	"Al-Ghashiya",
	89:	"Al-Fajr",
	90:	"Al-Balad",
	91:	"Ash-Shams",
	92:	"Al-Layl",
	93:	"Ad-Duha",
	94:	"Ash-Sharh",
	95:	"At-Tin",
	96:	"Al-'Alaq",
	97:	"Al-qadr",
	98:	"Al-Bayyinah",
	99:	"Az-Zalzala",
	100:	"Al-'Adiyat",
	101:	"Al-Qari'ah",
	102:	"At-Takathur",
	103:	"Al-'Asr",
	104:	"Al-Humazah",
	105:	"Al-Fil",
	106:	"Al-Quraish",
	107:	"Al-Ma'un",
	108:	"Al-Kauthar",
	109:	"Al-Kafirun",
	110:	"An-Nasr",
	111:	"Al-Masad",
	112:	"Al-Ikhlas",
	113:	"Al-Falaq",
	114:	"An-Nas"
}

quranSurahToNum = {
    "Al-Fatihah"        : 0,
    "Al-Baqarah"        : 1,
    "Al-Imran"          : 2,
    "An-Nisa'"          : 3,
    "Al-Ma'idah"        : 4,
    "Al-An'am"          : 5,
    "Al-A'raf"          : 6,
    "Al-Anfal"          : 7,
    "At-Taubah"         : 8,
    "Yunus"             : 9,
    "Hud"               : 10,
    "Yusuf"             : 11,
    "Ar-Ra'd"           : 12,
    "Ibrahim"           : 13,
    "Al-Hijr"           : 14,
    "An-Nahl"           : 15,
    "Al-Isra"           : 16,
    "Al-Kahf"           : 17,
    "Maryam"            : 18,
    "Ta Ha"             : 19,
    "Al-Anbiya'"        : 20,
    "Al-Hajj"           : 21,
    "Al-Mu'minun"       : 22,
    "An-Nur"            : 23,
    "Al-Furqan"         : 24,
    "Ash-Shu'ara"       : 25,
    "An-Naml"           : 26,
    "Al-Qasas"          : 27,
    "Al-'Ankabut"       : 28,
    "Ar-Rum"            : 29,
    "Luqman"            : 30,
    "As-Sajdah"         : 31,
    "Al-Ahzab"          : 32,
    "Saba'"             : 33,
    "Fatir"             : 34,
    "Ya Sin"            : 35,
    "As-Saffat"         : 36,
    "Sad"               : 37,
    "Az-Zumar"          : 38,
    "Ghafir"            : 39,
    "Fussilat"          : 40,
    "Ash-Shura"         : 41,
    "Az-Zukhruf"        : 42,
    "Ad-Dukhan"         : 43,
    "Al-Jathiyah"       : 44,
    "Al-Ahqaf"          : 45,
    "Muhammad"          : 46,
    "Al-Fath"           : 47,
    "Al-Hujurat"        : 48,
    "Qaf"               : 49,
    "Ad-Dhariyat"       : 50,
    "At-Tur"            : 51,
    "An-Najm"           : 52,
    "Al-Qamar"          : 53,
    "Ar-Rahman"         : 54,
    "Al-Waqi'ah"        : 55,
    "Al-Hadid"          : 56,
    "Al-Mujadilah"      : 57,
    "Al-Hashr"          : 58,
    "Al-Mumtahanah"     : 59,
    "As-Saff"           : 60,
    "Al-Jumu'ah"        : 61,
    "Al-Munafiqun"      : 62,
    "At-Taghabun"       : 63,
    "At-Talaq"          : 64,
    "At-Tahrim"         : 65,
    "Al-Mulk"           : 66,
    "Al-Qalam"          : 67,
    "Al-Haqqah"         : 68,
    "Al-Ma'arij"        : 69,
    "Nuh"               : 70,
    "Al-Jinn"           : 71,
    "Al-Muzammil"       : 72,
    "Al-Mudathir"       : 73,
    "Al-Qiyamah"        : 74,
    "Al-Insane"         : 75,
    "Al-Mursalat"       : 76,
    "An-Naba'"          : 77,
    "An-Nazi'at"        : 78,
    "'Abasa"            : 79,
    "At-Takwir"         : 80,
    "Al-Infitar"        : 81,
    "Al-Mutaffifeen"    : 82,
    "Al-Inshiqaq"       : 83,
    "Al-Buruj"          : 84,
    "At-Tariq"          : 85,
    "Al-A`la"           : 86,
    "Al-Ghashiya"       : 87,
    "Al-Fajr"           : 88,
    "Al-Balad"          : 89,
    "Ash-Shams"         : 90,
    "Al-Layl"           : 91,
    "Ad-Duha"           : 92,
    "Ash-Sharh"         : 93,
    "At-Tin"            : 94,
    "Al-'Alaq"          : 95,
    "Al-qadr"           : 96,
    "Al-Bayyinah"       : 97,
    "Az-Zalzala"        : 98,
    "Al-'Adiyat"        : 99,
    "Al-Qari'ah"        : 100,
    "At-Takathur"       : 101,
    "Al-'Asr"           : 102,
    "Al-Humazah"        : 103,
    "Al-Fil"            : 104,
    "Al-Quraish"        : 105,
    "Al-Ma'un"          : 106,
    "Al-Kauthar"        : 107,
    "Al-Kafirun"        : 108,
    "An-Nasr"           : 109,
    "Al-Masad"          : 110,
    "Al-Ikhlas"         : 111,
    "Al-Falaq"          : 112,
    "An-Nas"            : 113
}

bibleNumToBook = {
	0: "Genesis",
	1: "Exodus",
	2: "Leviticus",
	3: "Numbers",
	4: "Deuteronomy",
	5: "Joshua",
	6: "Judges",
	7: "Ruth",
	8: "1 Samuel",
	9: "2 Samuel",
	10: "1 Kings",
	11: "2 Kings",
	12: "1 Chronicles",
	13: "2 Chronicles",
	14: "Ezra",
	15: "Nehemiah",
	16: "Esther",
	17: "Job",
	18: "Psalms",
	19: "Proverbs",
	20: "Ecclesiastes",
	21: "Song of Solomon",
	22: "Isaiah",
	23: "Jeremiah",
	24: "Lamentations",
	25: "Ezekiel",
	26: "Daniel",
	27: "Hosea",
	28: "Joel",
	29: "Amos",
	30: "Obadiah",
	31: "Jonah",
	32: "Micah",
	33: "Nahum",
	34: "Habakkuk",
	35: "Zephaniah",
	36: "Haggai",
	37: "Zechariah",
	38: "Malachi",
	39: "Matthew",
	40: "Mark",
	41: "Luke",
	42: "John",
	43: "Acts",
	44: "Romans",
	45: "1 Corinthians",
	46: "2 Corinthians",
	47: "Galatians",
	48: "Ephesians",
	49: "Philippians",
	50: "Colossians",
	51: "1 Thessalonians",
	52: "2 Thessalonians",
	53: "1 Timothy",
	54: "2 Timothy",
	55: "Titus",
	56: "Philemon",
	57: "Hebrews",
	58: "James",
	59: "1 Peter",
	60: "2 Peter",
	61: "1 John",
	62: "2 John",
	63: "3 John",
	64: "Jude",
	65: "Revelation"
}

bibleBookToNum = {
	"Genesis"			: 0,
	"Exodus"			: 1,
	"Leviticus"			: 2,
	"Numbers"			: 3,
	"Deuteronomy"		: 4,
	"Joshua"			: 5,
	"Judges"			: 6,
	"Ruth"				: 7,
	"1 Samuel"			: 8,
	"2 Samuel"			: 9,
	"1 Kings"			: 10,
	"2 Kings"			: 11,
	"2 Chronicles"		: 12,
	"1 Chronicles"		: 13,
	"Ezra"				: 14,
	"Nehemiah"			: 15,
	"Esther"			: 16,
	"Job"				: 17,
	"Psalms"			: 18,
	"Proverbs"			: 19,
	"Ecclesiastes"		: 20,
	"Song of Solomon"	: 21,
	"Isaiah"			: 22,
	"Jeremiah"			: 23,
	"Lamentations"		: 24,
	"Ezekiel"			: 25,
	"Daniel"			: 26,
	"Hosea"				: 27,
	"Joel"				: 28,
	"Amos"				: 29,
	"Obadiah"			: 30,
	"Jonah"				: 31,
	"Micah"				: 32,
	"Nahum"				: 33,
	"Habakkuk"			: 34,
	"Zephaniah"			: 35,
	"Haggai"			: 36,
	"Zechariah"			: 37,
	"Malachi"			: 38,
	"Matthew"			: 39,
	"Mark"				: 40,
	"Luke"				: 41,
	"Acts"				: 42,
	"John"				: 43,
	"Romans"			: 44,
	"1 Corinthians"		: 45,
	"2 Corinthians"		: 46,
	"Galatians"			: 47,
	"Ephesians"			: 48,
	"Philippians"		: 49,
	"Colossians"		: 50,
	"1 Thessalonians"	: 51,
	"2 Thessalonians"	: 52,
	"1 Timothy"			: 53,
	"2 Timothy"			: 54,
	"Titus"				: 55,
	"Philemon"			: 56,
	"Hebrews"			: 57,
	"James"				: 58,
	"1 Peter"			: 59,
	"2 Peter"			: 60,
	"1 John"			: 61,
	"2 John"			: 62,
	"3 John"			: 63,
	"Jude"				: 64,
	"Revelation"		: 65
}

def getSurahFromNum(num):
    if num in quranNumToSurah:
        return quranNumToSurah[num]
    else:
        return None
def getNumFromSurah(surah):
    if surah in quranSurahToNum:
        return quranSurahToNum[surah]
    else:
        return None
def getBookFromNum(num):
    if num in bibleNumToBook:
        return bibleNumToBook[num]
    else:
        return None
def getNumFromBook(book):
    if book in bibleBookToNum:
        return bibleBookToNum[book]
    else:
        return None